from typing import Dict, List

from actions import Action


SHORTCUTS: Dict[str, List[dict]] = {
    "new_tab": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 17},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 17},
        {"type": "release_key", "key_code": 55},
    ],
    "new_window": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 45},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 45},
        {"type": "release_key", "key_code": 55},
    ],
    "new_incognito_window": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 56},
        {"type": "press_key", "key_code": 45},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 45},
        {"type": "release_key", "key_code": 56},
        {"type": "release_key", "key_code": 55},
    ],
    "reopen_closed_tab": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 56},
        {"type": "press_key", "key_code": 17},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 17},
        {"type": "release_key", "key_code": 56},
        {"type": "release_key", "key_code": 55},
    ],
    "close_tab": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 13},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 13},
        {"type": "release_key", "key_code": 55},
    ],
    "close_window": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 56},
        {"type": "press_key", "key_code": 13},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 13},
        {"type": "release_key", "key_code": 56},
        {"type": "release_key", "key_code": 55},
    ],
    "next_tab": [
        {"type": "press_key", "key_code": 59},
        {"type": "press_key", "key_code": 48},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 48},
        {"type": "release_key", "key_code": 59},
    ],
    "previous_tab": [
        {"type": "press_key", "key_code": 59},
        {"type": "press_key", "key_code": 56},
        {"type": "press_key", "key_code": 48},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 48},
        {"type": "release_key", "key_code": 56},
        {"type": "release_key", "key_code": 59},
    ],
    "go_to_tab_1": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 18},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 18},
        {"type": "release_key", "key_code": 55},
    ],
    "go_to_tab_2": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 19},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 19},
        {"type": "release_key", "key_code": 55},
    ],
    "go_to_tab_3": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 20},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 20},
        {"type": "release_key", "key_code": 55},
    ],
    "go_to_tab_4": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 21},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 21},
        {"type": "release_key", "key_code": 55},
    ],
    "go_to_tab_5": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 23},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 23},
        {"type": "release_key", "key_code": 55},
    ],
    "go_to_tab_6": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 22},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 22},
        {"type": "release_key", "key_code": 55},
    ],
    "go_to_tab_7": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 26},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 26},
        {"type": "release_key", "key_code": 55},
    ],
    "go_to_tab_8": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 28},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 28},
        {"type": "release_key", "key_code": 55},
    ],
    "go_to_last_tab": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 25},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 25},
        {"type": "release_key", "key_code": 55},
    ],
    "move_tab_left": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 58},
        {"type": "press_key", "key_code": 123},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 123},
        {"type": "release_key", "key_code": 58},
        {"type": "release_key", "key_code": 55},
    ],
    "move_tab_right": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 58},
        {"type": "press_key", "key_code": 124},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 124},
        {"type": "release_key", "key_code": 58},
        {"type": "release_key", "key_code": 55},
    ],
    "reload": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 15},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 15},
        {"type": "release_key", "key_code": 55},
    ],
    "hard_reload": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 56},
        {"type": "press_key", "key_code": 15},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 15},
        {"type": "release_key", "key_code": 56},
        {"type": "release_key", "key_code": 55},
    ],
    "stop_loading": [
        {"type": "press_key", "key_code": 53},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 53},
    ],
    "back_arrow": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 123},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 123},
        {"type": "release_key", "key_code": 55},
    ],
    "back_bracket": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 33},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 33},
        {"type": "release_key", "key_code": 55},
    ],
    "forward_arrow": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 124},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 124},
        {"type": "release_key", "key_code": 55},
    ],
    "forward_bracket": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 30},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 30},
        {"type": "release_key", "key_code": 55},
    ],
    "open_file": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 31},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 31},
        {"type": "release_key", "key_code": 55},
    ],
    "print": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 35},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 35},
        {"type": "release_key", "key_code": 55},
    ],
    "save_page_as": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 1},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 1},
        {"type": "release_key", "key_code": 55},
    ],
    "find": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 3},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 3},
        {"type": "release_key", "key_code": 55},
    ],
    "find_next": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 5},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 5},
        {"type": "release_key", "key_code": 55},
    ],
    "find_previous": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 56},
        {"type": "press_key", "key_code": 5},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 5},
        {"type": "release_key", "key_code": 56},
        {"type": "release_key", "key_code": 55},
    ],
    "zoom_in": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 56},
        {"type": "press_key", "key_code": 24},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 24},
        {"type": "release_key", "key_code": 56},
        {"type": "release_key", "key_code": 55},
    ],
    "zoom_out": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 27},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 27},
        {"type": "release_key", "key_code": 55},
    ],
    "reset_zoom": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 29},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 29},
        {"type": "release_key", "key_code": 55},
    ],
    "full_screen": [
        {"type": "press_key", "key_code": 59},
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 3},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 3},
        {"type": "release_key", "key_code": 55},
        {"type": "release_key", "key_code": 59},
    ],
    "focus_address_bar": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 37},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 37},
        {"type": "release_key", "key_code": 55},
    ],
    "open_location": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 37},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 37},
        {"type": "release_key", "key_code": 55},
    ],
    "open_search_in_new_tab": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 36},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 36},
        {"type": "release_key", "key_code": 55},
    ],
    "show_bookmarks_bar": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 56},
        {"type": "press_key", "key_code": 11},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 11},
        {"type": "release_key", "key_code": 56},
        {"type": "release_key", "key_code": 55},
    ],
    "bookmark_this_tab": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 2},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 2},
        {"type": "release_key", "key_code": 55},
    ],
    "bookmark_manager": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 58},
        {"type": "press_key", "key_code": 11},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 11},
        {"type": "release_key", "key_code": 58},
        {"type": "release_key", "key_code": 55},
    ],
    "history": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 16},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 16},
        {"type": "release_key", "key_code": 55},
    ],
    "downloads": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 56},
        {"type": "press_key", "key_code": 38},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 38},
        {"type": "release_key", "key_code": 56},
        {"type": "release_key", "key_code": 55},
    ],
    "toggle_devtools": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 58},
        {"type": "press_key", "key_code": 34},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 34},
        {"type": "release_key", "key_code": 58},
        {"type": "release_key", "key_code": 55},
    ],
    "console": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 58},
        {"type": "press_key", "key_code": 38},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 38},
        {"type": "release_key", "key_code": 58},
        {"type": "release_key", "key_code": 55},
    ],
    "inspect_element": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 56},
        {"type": "press_key", "key_code": 8},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 8},
        {"type": "release_key", "key_code": 56},
        {"type": "release_key", "key_code": 55},
    ],
    "view_source": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 58},
        {"type": "press_key", "key_code": 32},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 32},
        {"type": "release_key", "key_code": 58},
        {"type": "release_key", "key_code": 55},
    ],
    "open_new_tab_background": [
        {"type": "press_key", "key_code": 55},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 55},
    ],
    "open_link_new_tab": [
        {"type": "press_key", "key_code": 55},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 55},
    ],
    "open_link_new_window": [
        {"type": "press_key", "key_code": 56},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 56},
    ],
    "quit_chrome": [
        {"type": "press_key", "key_code": 55},
        {"type": "press_key", "key_code": 12},
        {"type": "wait", "seconds": 0.1},
        {"type": "release_key", "key_code": 12},
        {"type": "release_key", "key_code": 55},
    ],
}


def resolve_shortcut(name: str) -> List[Action]:
    if name not in SHORTCUTS:
        raise ValueError(f"Unknown shortcut: {name}")
    return [Action.model_validate(item) for item in SHORTCUTS[name]]
